name: upwork
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.8.3
  - beautifulsoup4=4.9.1
  - requests=2.24.0
  - pandas=1.0.5
  - tqdm=4.47.0
  - pip=20.1.1
  - pip:
    - lxml==4.5.2
